import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import SectionTitle from '../components/SectionTitle';
import PrestationItem from '../components/items/PrestationItem';
import ImagePrestationBuildWebsite from '../public/images/prestations/creation-site-internet.png';
import ImagePrestationTma from '../public/images/prestations/infogerance-tma-maintenance.png';
import ImagePrestationHosting from '../public/images/prestations/hebergement-optimise-rapide.png';
import Diagonal from '../components/layouts/Diagonal';
import ImageDiscoverTma from '../public/images/prestations/presentation-integration-web.jpeg';
import ProjectItem from '../components/items/ProjectItem';
import MoreIcon from '../components/icons/MoreIcon';
import ContactForm from '../components/ContactForm';
import ExpertiseItem from '../components/items/ExpertiseItem';
import ExpertiseWordPress from '../public/images/expertises/wordpress.png';
import ExpertiseSymfony from '../public/images/expertises/symfony.png';
import ExpertisePrestashop from '../public/images/expertises/prestashop.png';
import ExpertiseJoomla from '../public/images/expertises/joomla.png';
import Keypoints from '../components/Keypoints';
import ArticleItem from '../components/items/ArticleItem';
import LeafHeartIcon from '../components/icons/LeafHeartIcon';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <SectionTitle
          className="mt-3 md:mt-0"
          title="A propos"
          content="Développeur Freelance créatif et innovant basé au coeur de La Rochelle et spécialisé dans la création de site internet. Depuis l'âge de 14 ans, je développe, compose et crée des projets web."
        />

        <div className="my-4 mx-auto text-xl sm:text-2xl max-w-4xl font-medium text-center text-white">
          Je suis entouré d&apos;une équipe fondée de créatifs, designers et développeurs.
          Nous travaillons ensemble pour créer des choses inspirantes et engagées.
        </div>

        <div className="grid md:grid-cols-3 gap-6 md:gap-3 lg:gap-6">
          <PrestationItem
            image={ImagePrestationBuildWebsite}
            title={['Conception / Refonte', <br />, 'de sites Internet']}
            link="/"
            linkText="Découvrir mes prestations"
          >
            Sites vitrines, associatifs, e-commerce ou dédiés.
            Je vous accompagne dès la genèse de votre projet pour vous proposer
            des solutions puissantes et performantes et répondre le plus efficacement
            aux enjeux de votre activité. Je suis expert dans la création de site sur les CMS
            Joomla, WordPress et Prestashop.
          </PrestationItem>

          <PrestationItem
            image={ImagePrestationTma}
            title={['Maintenance &', <br />, 'Infogérance']}
            link="/"
            linkText="Mes offres de maintenance"
          >
            La maintenance d’un site internet s’avère complexe lorsqu’on ne dispose pas
            du bagage technique nécessaire voire le temps de s’en occuper.
            Pour ces tâches délicates et chronophages, je vous propose de prendre le
            relai et d’assurer pour vous la gestion de vos sauvegardes, ainsi que la
            maintenance et la sécurité de votre serveur dans sa globalité.
          </PrestationItem>

          <PrestationItem
            image={ImagePrestationHosting}
            title={['Hébergement optimisé &', <br />, 'ultra rapide']}
            link="/"
            linkText="Me contacter"
          >
            Lorsque vous souhaitez mettre en ligne un site, il est nécessaire de choisir
            une offre d’hébergement parmis une foule d’offres et de prestataires.
            Nos offres d’hébergement sont transparentes et sans frais cachés.
            Un expert de notre partenaire Dutiko analyse votre projet ainsi que votre demande
            pour vous proposer l’offre idéale pour la nature de votre site web.
          </PrestationItem>
        </div>
      </div>

      <div className="relative">
        <Diagonal
          className="-z-10"
          flipX
          flipY
          bgClass="fill-gray-dark"
          bgCorner="fill-orange"
        />
        <Image layout="fill" objectFit="cover" className="-z-10 opacity-30 md:opacity-100" src={ImageDiscoverTma} alt="Prestation de maintenance TMA" />
        <div className="container relative -my-10">
          <div className="md:w-1/2">
            <h2 className="text-2xl sm:text-3xl text-white font-medium mb-3">
              Besoin d’une estimation de votre site
              <br className="hidden sm:block" />
              et/ou de sa maintenance
            </h2>
            <p>
              Simple et en toute transparence, n’hésitez pas à me demander une estimation
              gratuite pour la création de votre site web ou de la maintenance applicative.
            </p>
            <p>
              Vous recevrez dans la journée votre devis et nous pourrons prendre contact pour
              définir ensemble les tâches.
            </p>

            <div className="flex flex-wrap flex-start">
              <Link href="/">
                <a className="button mt-3 mr-2">Demandez votre devis maintenant</a>
              </Link>
              <Link href="/">
                <a className="button-outline mt-3">Mes offres de maintenance</a>
              </Link>
            </div>
          </div>
        </div>
        <Diagonal
          className="-z-10"
          bgClass="fill-gray-darker"
          bgCorner="fill-orange"
        />
      </div>

      <div className="bg-gray-darker">
        <div className="container -mb-8">
          <SectionTitle
            content="Consultez mes dernières créations, atteignant tous, l’esthétique du détail et de la fonctionnalité qui me démarque du reste en tant que développeur Freelance."
            title="Projets"
          />

          <div className="mt-3 sm:mt-0 grid gap-2 sm:gap-0 grid-cols-2 md:grid-cols-4">
            <ProjectItem
              image="/images/portfolio/biosalines-3d.jpeg"
              title="Laboratoires Biosalines"
              category="WordPress"
            />
            <ProjectItem
              image="/images/portfolio/biosalines-3d.jpeg"
              title="Laboratoires Biosalines"
              category="WordPress"
            />
            <ProjectItem
              image="/images/portfolio/biosalines-3d.jpeg"
              title="Laboratoires Biosalines"
              category="WordPress"
            />
            <ProjectItem
              image="/images/portfolio/biosalines-3d.jpeg"
              title="Laboratoires Biosalines"
              category="WordPress"
            />
          </div>
        </div>

        <Diagonal
          className="-z-10"
          bgClass="fill-gray-dark"
          bgCorner="fill-orange"
          cta={{
            icon: <MoreIcon />,
            title: ['Voir tous', <br />, 'les projets'],
            href: '/',
          }}
        />
      </div>

      <div className="container">
        <SectionTitle
          title="Expertises"
          content="Je propose un large éventail de services axés sur les résultats pour les marques, en veillant à ce que leur présence en ligne reflète réellement leurs objectifs et leurs inspirations."
        />

        <div className="my-4 grid md:grid-cols-2 gap-x-2 gap-y-6">
          <ExpertiseItem
            title="WordPress"
            excerpt="WordPress est le plus populaire des CMS en ce moment, il vous permet d’administrer facilement votre site et de personnaliser intégralement le frontoffice."
            link="/"
            image={ExpertiseWordPress}
          />
          <ExpertiseItem
            title="Symfony"
            excerpt="Symfony est un framework PHP qui nous permet d’accélèrer le développement de sites ou d’applications grace à sa méthodologie et architecture évolutive."
            link="/"
            image={ExpertiseSymfony}
          />
          <ExpertiseItem
            title="Prestashop"
            excerpt="Prestashop est un CMS très puissant pour les sites de commerce électronique (e-commerce) avec plus de 5 000 modules et thèmes."
            link="/"
            image={ExpertisePrestashop}
          />
          <ExpertiseItem
            title="Joomla"
            excerpt="Joomla est un CMS puissant en terme de pérénité, modularité et de puissance dans la gestion de contenu et de l’ajout de vos développement spécifique."
            link="/"
            image={ExpertiseJoomla}
          />
        </div>
      </div>

      <Keypoints />

      <div className="bg-gray-darker">
        <div className="container py-4">
          <SectionTitle
            content={"Passionné par les nouvelles technologies, j'adore partager mes compétences et mes découvertes avec des personnes qui ont cette même passion pour le web !"}
            title="Articles"
          />

          <div className="grid md:grid-cols-2 gap-4 -mb-8 mt-6">
            <ArticleItem
              image="/images/articles/bloc-gutenberg-wordpress-sage.jpeg"
              title="Blocs Gutenberg avec Sage 9 sur WordPress"
              excerpt="Découvrons comment organiser son thème WordPress sur le moteur Sage 9 pour créer et gérer ses différents blocs Gutenberg avec ACF directement depuis notre thème."
            />

            <ArticleItem
              image="/images/articles/server-mysql-replication.jpeg"
              title="Créer un serveur MySQL de réplication (slave) des données existantes"
              excerpt="MySQL Master-Slave Replication est une procédure permettant de répliquer en temps réel les données d’un serveur MySQL vers un autre. Nous allons voir ensemble comment mettre cette combinaison en place. Nous ne sommes pas à l’abri d’un incident sur nos serveurs de production et cela même avec un backup journalier de nos bases de données."
            />
          </div>
        </div>

        <Diagonal
          className="-z-10"
          bgClass="fill-gray-dark"
          bgCorner="fill-orange"
          cta={{
            icon: <LeafHeartIcon />,
            title: ['Voir tous', <br />, 'les articles'],
            href: '/',
          }}
        />
      </div>

      <div className="container">
        <SectionTitle
          content={"Pour toute demande ou devis, n'hésitez pas à me contacter en remplissant le formulaire ci-dessous, je serais ravis de vous répondre."}
          title="Contact"
        />

        <ContactForm />
      </div>
    </div>
  );
}
